language: dart

dart:
  - beta

env:
  global:
    secure: "XO2B4NeUiZu8IJlTbipsoqguUSK579bILyTYTrOOOK4h4iwOG+bAKLR6oZshYAlrh6WSrhyYcCUpTwn6or2V1mIPGUtlUgq0bPcEauqiizTxzdcMz5ckaqrxzcXXMpVA6bhxMT1B7lyJs9/UInimzcqLJQTjA20f9qjhchU2G3vvTIGng0YV/QZ0te/qbdWyGk8ys14wY2/4+Ev8+JDIJxs4O7iNqellGDQwDujQb8nutQNUg6QMQzstKOm6KH0s0EV7Q37gtzVheStg85+KtOyV3jz9bG7kzxQJkohn02tOgIh+ZVXVReTyLZTRVEeUJIERNhr8WfozZy4+GfcMbSKk34jJgamG1j+ZAlJ1nEte5ZJuoDU6Ebatjv/Z93UyXriNJgLCqn857lrU5bY6Qe67Vamx5MIrw84d4kiEUsQ18kT/BGjMUSTBVDl96YxO+z1jFhEx4M05N/6HnhplmYzrJgu95jELokBAdusejPTDrQ504XxNydZlwjwstCjOwIR1GQj6u1P3Cws99sdl3CpaNzw9R/uUOhG0jFflQeimFns+KtqT64BxGAZizoStl4uP4k/PJ/tPlJp0nSDJBktHT1tKq0QKojJHiwuWPrbtRcKOAxU7DpSOJIAMTUEPPsUI2DhNk7sqTpzgQJjsZlACA/1s84mJKvXb/4yF2Oc="
    secure: "H41t10kw2ewFRNDcTg1oZu+Iz9w8Rs4MSjGgfi5ysvurTtkTq80TXQY+bPAEojHa8aI/l7EV55ErZN1JhmbUkAcySF67rgKPU6IKiiH2X301OvSIJGsS8mQn5jrx6IUAwtwGvqeOrsgnG5qr8dBI9LL5MRokvgTqt7iNP9hocPPb8ubiFPrSUOkTAlIZxCUYgQQRU+W6aaJmKfAVTbjmCgCFpnvDeabnv0ZWxqL9vXh4CIGD6L//ouAn0TZl1dk0txxGMDEppbfuqZ9rcfrNJhjhCR4U/gkwGGc+Kn3UeXrtmencetw8B063tcpBizHCkY7zQbG407shIBXURCOCwOPG1DmkVFnXnqRyMjC5zmM4sXV8Mp+uNTMxFD24rARrjNptl9hgRxPnbbfBm3D1cCmfybnwbVt/IXVKPDXrfWxXlU9AbazQ3koHCkppDC5+8cxZh3TOV6czJCwAWEBhme4tVTIQh3U9uWeGnTScopkW2BSpIsqRoKPuqy5kNyit4+Q9XW2RtqrJQ+tHBDLnORtuK7Vz2GSohSHsOhg6DdNIlIV4yCdOUJudCA+jGYhowYyCuQH+5pdWZ6ksKRuu0QO28RAPQiNFmbQZQk35dajeob8BdZbF2oPUXqkhE7pBHbwwJikEYIDDEMAA0p656G+B6Jj1Hf41Ee7CHRXknPk="
    secure: "FA/n5DRdlaqTG9e14V0x/6KsUYmQXj7kcVTTsBP9cTsxwmum1yd9dnFvWYZgLTP7kVdukC5Qm+QnPpuL7p7uObCLYw5xTjgbOan1SXno1gRdsjXK04iuqVN/pbFr5tuX0rMbjnaHz6OYhDAstAF+JB+OT3MQbAf5+srOVlJySRcDZQjyzuWm7ULEe7PWfMWoKC8XDxr1cK9dMRUHdAZT6jvCiJx4WvdaiM0C9WxfE1YfiguHGGhFX9mXUArd++U4hb8cQJtZ4CSRuHqhZgDY5DriOhIHKXTj4OPVMlmLV12/SH/c2PSB2LLywqQ/kEl0OLgMFAMejIOBQrzi+0NK+BLJTRmrGMfmXg/TKb58yGVPjcEH+m3k7vHS4H1XZICYBj/kDdBEKyRIGDWe1oI2w5XsXJOi8BWSHbSj45Q+ZyQURwtFSg2K/QZXKDEbYl+haf/K6wKWT7detHpFxgBg/2wdBZLa6h2QUhmXAyPQcnD2Rl3JFhlLnbrIjf80Bf23Y8W0Jei42GjraEkvtj3b12/Nfbe6R5uYvYLfThicpJzLlWBgph/iXiYK48tWYmB+7P0zhq/l1VPj/FuizxNysr+S4Z1SMj44TkLwJxlDUm2Uer1tjwQiA5V0GNhza2n0ewFWxq3uvTOVeclddhlR6t23tkVtlnPRPrcZg5Vye28="

jobs:
  include:
    # 删除 env 文件，防止被其覆盖 travis 里配置的环境变量
    - stage: delete_env_file
      name: 'delete env file'
      os: linux
      script: echo $QINIU_DART_SDK_ACCESS_KEY && rm -fr .env
    # 检查 lint 并在 warnings、infos 时报错退出
    - stage: analyze_and_format
      name: "Analyze"
      os: linux
      script: dartanalyzer --fatal-warnings --fatal-infos .

    # 检查格式并在异常时退出
    - stage: analyze_and_format
      name: "Format"
      os: linux
      script: dartfmt -n --set-exit-if-changed .

    # 执行测试（已开启 null safe）
    - stage: test
      name: "Vm Tests"
      os: linux
      script: pub run --enable-experiment=non-nullable test

stages:
  - delete_env_file
  - analyze_and_format
  - test

cache:
  directories:
    - $HOME/.pub-cache
