name: qiniu_sdk_base
version: 0.0.1
homepage: https://qiniu.com
description: The sdk basic of Qiniu business lines

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  dio: ^3.0.10
  crypto: ^2.1.5
  meta: ^1.2.3

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
